### ISSUE TITLE
RFE: Make robust to PATH

### ISSUE THREAD

**Issue by vanderwb** [NCAR/mpibind#2]
Right now, `mpibind` seems to fail if `gpu_bind` or `cpu_bind` are not in the PATH. I'd suggest adding code to allow `mpibind` to locate itself, and then call those sub-scripts appropriately via relative or absolute paths to make things more robust.

**Comment by roryck** [comment]
Sounds like a perfectly good idea. Thanks for testing, it's on the list

**Comment by roryck** [comment]
resolved by https://github.com/NCAR/mpibind/commit/44d6f83e79ca1c71cc1a8d5911ef91fd979b52fa
